name: lpmi40
description: A new Flutter project for displaying and managing song lyrics with customizable themes and settings.
publish_to: 'none' # Prevents publishing to pub.dev

version: 1.8.0+8

environment:
  sdk: ">=2.18.0 <3.0.0" # Ensure compatibility with the latest Dart SDK versions

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0 # For saving user settings
  share_plus: ^10.0.2 # For sharing song lyrics
  win32: ^5.5.4 # Windows-specific functionality, if targeting Windows platform
  auto_size_text: ^3.0.0 # For auto-sizing the song title text
  intl: ^0.20.1
  flutter_speed_dial: ^7.0.0
  url_launcher: ^6.0.9
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_in_app_messaging: ^0.8.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # For enforcing best practices and linting rules
  flutter_launcher_icons: ^0.14.1 # Add this line for app icon generation

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true

  # Assets used in the application
  assets:
    - assets/lpmi.json
    - assets/images/header_image.png
