name: lpmi40
description: A new Flutter project for displaying and managing song lyrics with customizable themes and settings.
publish_to: 'none'

version: 2.2.0+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Material Design
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  intl: ^0.20.1
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.2.1
  
  # Device & Platform Integration
  shared_preferences: ^2.1.0
  url_launcher: ^6.0.9

  # ✅ FIXED: Compatible Firebase Services for Web (Kotlin 1.9.x compatible)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_database: ^10.4.0
  firebase_storage: ^11.5.4
  
  # Additional Firebase Services - Compatible versions
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.14.0
  firebase_remote_config: ^4.3.8
  
  # Authentication & User Management
  # google_sign_in: ^6.1.5  # Removed - not needed
  
  # File & Media Management
  image_picker: ^1.0.7
  path_provider: ^2.0.15
  path: ^1.8.3
  #image_gallery_saver: ^2.0.3
  flutter_email_sender: ^7.0.0
  
  # State Management
  provider: ^6.1.5
  
  # Network & HTTP
  http: ^1.1.0
  
  # Additional dependencies for sharing functionality
  share_plus: ^7.2.2
  package_info_plus: ^8.3.0
  file_picker: ^10.2.0
  just_audio: ^0.10.4
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/icons/