name: lpmi_24
description: A new Flutter project for displaying and managing song lyrics with customizable themes and settings.
publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0" # Ensure compatibility with the latest Dart SDK versions

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0 # For saving user settings
  share_plus: ^6.3.0 # For sharing song lyrics
  win32: ^3.1.4 # Windows-specific functionality, if targeting Windows platform
  auto_size_text: ^3.0.0 # For auto-sizing the song title text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 # For enforcing best practices and linting rules

flutter:
  uses-material-design: true

  # Assets used in the application
  assets:
    - assets/lpmi.json
    - assets/header_image.png
