name: lpmi40
description: A new Flutter project for displaying and managing song lyrics with customizable themes and settings.
publish_to: 'none'

version: 2.1.0+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Material Design
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  intl: ^0.20.1
  flutter_speed_dial: ^7.0.0
  
  # Device & Platform Integration
  shared_preferences: ^2.1.0
  url_launcher: ^6.0.9

  # Firebase Services (Core only - add others gradually)
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_database: ^11.3.7
  
  # Add these after basic build works:
  # firebase_analytics: ^11.5.0
  # firebase_crashlytics: ^4.3.7
  # firebase_messaging: ^15.2.7
  # cloud_firestore: ^5.6.9
  # firebase_remote_config: ^5.4.5
  
  # Authentication & User Management
  # google_sign_in: ^7.0.0  # Add after Firebase setup complete
  
  # File & Media Management
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.8.3
  
  # State Management
  provider: ^6.1.5
  
  # Network & HTTP
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/icons/