// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwTI5DB8386-LS_jcOXR3Z7dS48qtaEVU',
    appId: '1:1065655353423:android:0a306011e4b4488037aa3a',
    messagingSenderId: '1065655353423',
    projectId: 'lmpi-c5c5c',
    databaseURL: 'https://lmpi-c5c5c-default-rtdb.firebaseio.com',
    storageBucket: 'lmpi-c5c5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALvyjpgnmzywkIIo5bxSJJ-tkPHhNKmEg',
    appId: '1:1065655353423:ios:d7e1f1424adc097737aa3a',
    messagingSenderId: '1065655353423',
    projectId: 'lmpi-c5c5c',
    databaseURL: 'https://lmpi-c5c5c-default-rtdb.firebaseio.com',
    storageBucket: 'lmpi-c5c5c.firebasestorage.app',
    iosClientId:
        '1065655353423-7f5i768ddds9041cjphfarhja8936mpf.apps.googleusercontent.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwTI5DB8386-LS_jcOXR3Z7dS48qtaEVU',
    appId: '1:1065655353423:web:0a306011e4b4488037aa3a',
    messagingSenderId: '1065655353423',
    projectId: 'lmpi-c5c5c',
    databaseURL: 'https://lmpi-c5c5c-default-rtdb.firebaseio.com',
    storageBucket: 'lmpi-c5c5c.firebasestorage.app',
    authDomain: 'lmpi-c5c5c.firebaseapp.com',
  );
}
