-keep class com.google.firebase.** { *; }
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.** { *; }
-keep class com.google.android.play.core.** { *; }
-keepattributes *Annotation*
-dontwarn com.google.firebase.**
-dontwarn com.google.android.play.core.**